name: Create a pre-release

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/pre-release.yml

permissions:
  contents: write

jobs:
  create-pre-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: |
          npm run build
          npm pack .

      - name: Delete previous pre-release
        run: gh release delete --yes bleeding-edge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pre-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: bleeding-edge
          body: Pre-release with the latest commits
          files: npm-package-*.tgz
