name: Create a release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  create-pre-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: |
          npm run build
          npm pack .

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pre-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          body: ${{ steps.changelog.outputs.changes }}
          files: npm-package-*.tgz
